import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../data/models/report_summary_model.dart';
import 'package:intl/intl.dart';
import 'package:flutter/foundation.dart';

class PdfService {
  static Future<void> generateAndPrintReport({
    required String messName,
    required ReportSummaryModel summary,
    required List<MemberSummaryModel> members,
  }) async {
    debugPrint('PdfService generateAndPrintReport called for mess: $messName');
    final pdf = pw.Document();

    final monthName = DateFormat('MMMM yyyy').format(DateTime(summary.year, summary.month));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(messName, monthName),
            pw.SizedBox(height: 20),
            _buildSummaryCard(summary),
            pw.SizedBox(height: 20),
            _buildMemberTable(members),
            pw.SizedBox(height: 30),
            _buildFooter(),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Mess_Report_$monthName.pdf',
    );
  }

  static pw.Widget _buildHeader(String messName, String monthName) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          messName,
          style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'Monthly Summary Report - $monthName',
          style: const pw.TextStyle(fontSize: 16, color: PdfColors.grey700),
        ),
        pw.Divider(thickness: 2),
      ],
    );
  }

  static pw.Widget _buildSummaryCard(ReportSummaryModel summary) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
        children: [
          _summaryItem('Total Meals', summary.totalMeals.toStringAsFixed(1)),
          _summaryItem('Total Expenses', 'Tk ${summary.totalExpenses.toStringAsFixed(2)}'),
          _summaryItem('Meal Rate', 'Tk ${summary.mealRate.toStringAsFixed(2)}'),
        ],
      ),
    );
  }

  static pw.Widget _summaryItem(String title, String value) {
    return pw.Column(
      children: [
        pw.Text(title, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.grey600)),
        pw.SizedBox(height: 4),
        pw.Text(value, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  static pw.Widget _buildMemberTable(List<MemberSummaryModel> members) {
    return pw.TableHelper.fromTextArray(
      headers: ['Member Name', 'Total Meals', 'Total Cost', 'Total Deposits', 'Final Balance'],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.deepPurple),
      cellHeight: 30,
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerRight,
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
      data: members.map((m) {
        return [
          m.userName,
          m.totalMeals.toStringAsFixed(1),
          m.totalCost.toStringAsFixed(2),
          m.totalDeposits.toStringAsFixed(2),
          m.finalBalance.toStringAsFixed(2),
        ];
      }).toList(),
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(),
        pw.SizedBox(height: 8),
        pw.Text(
          'Generated by Bachelor Points App',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
        ),
      ],
    );
  }
}
