// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjCtu405z5irpADsalnlZhjK_cyjocCw4',
    appId: '1:225274585167:web:d92fa3afb4c4fa41f80a3a',
    messagingSenderId: '225274585167',
    projectId: 'bachelorpoints-solutions',
    authDomain: 'bachelorpoints-solutions.firebaseapp.com',
    storageBucket: 'bachelorpoints-solutions.firebasestorage.app',
    measurementId: 'G-1L8DST4HH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAhRkB1o7ba2_KhS2Kb7phbmwoIGMtOc',
    appId: '1:225274585167:android:c5e15ce775ce12e1f80a3a',
    messagingSenderId: '225274585167',
    projectId: 'bachelorpoints-solutions',
    storageBucket: 'bachelorpoints-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gvnsHG1gDcs1fRIO4-9LapdMVrhd8Fw',
    appId: '1:225274585167:ios:1335e811e10d64ebf80a3a',
    messagingSenderId: '225274585167',
    projectId: 'bachelorpoints-solutions',
    storageBucket: 'bachelorpoints-solutions.firebasestorage.app',
    iosBundleId: 'com.messmanager.bachelorpoints',
  );
}
