class BazarScheduleModel {
  final String id;
  final String messId;
  final String userId;
  final DateTime date;
  
  // Joined from profiles table
  final String? userName;

  BazarScheduleModel({
    required this.id,
    required this.messId,
    required this.userId,
    required this.date,
    this.userName,
  });

  factory BazarScheduleModel.fromJson(Map<String, dynamic> json) {
    return BazarScheduleModel(
      id: json['id'] as String,
      messId: json['mess_id'] as String,
      userId: json['user_id'] as String,
      date: _parseDateTime(json['date']),
      userName: json['profiles']?['full_name'] as String?,
    );
  }

  static DateTime _parseDateTime(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is DateTime) return value;
    if (value is String) return DateTime.parse(value);
    return (value as dynamic).toDate() as DateTime;
  }

  Map<String, dynamic> toJson() {
    return {
      'mess_id': messId,
      'user_id': userId,
      'date': "${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}",
      // 'id' is generated by db
    };
  }
}
