import 'package:cloud_firestore/cloud_firestore.dart';

class MessageModel {
  final String id;
  final String messId;
  final String userId;
  final String senderName;
  final String message;
  final DateTime createdAt;

  MessageModel({
    required this.id,
    required this.messId,
    required this.userId,
    required this.senderName,
    required this.message,
    required this.createdAt,
  });

  factory MessageModel.fromJson(Map<String, dynamic> json) {
    return MessageModel(
      id: json['id'] as String,
      messId: json['mess_id'] as String,
      userId: json['user_id'] as String,
      senderName: json['sender_name'] as String? ?? 'Unknown',
      message: json['message'] as String,
      createdAt: _parseDateTime(json['created_at']),
    );
  }

  static DateTime _parseDateTime(dynamic value) {
    if (value == null) return DateTime.now();
    if (value is DateTime) return value;
    if (value is Timestamp) return value.toDate();
    if (value is String) {
      if (value.isEmpty) return DateTime.now();
      return DateTime.parse(value);
    }
    try {
      return (value as dynamic).toDate() as DateTime;
    } catch (_) {
      return DateTime.now();
    }
  }

  Map<String, dynamic> toJson() {
    return {
      'mess_id': messId,
      'user_id': userId,
      'sender_name': senderName,
      'message': message,
      // 'id' and 'created_at' are typically auto-generated by Supabase
    };
  }
}
