class MessageModel {
  final String id;
  final String messId;
  final String userId;
  final String senderName;
  final String message;
  final DateTime createdAt;

  MessageModel({
    required this.id,
    required this.messId,
    required this.userId,
    required this.senderName,
    required this.message,
    required this.createdAt,
  });

  factory MessageModel.fromJson(Map<String, dynamic> json) {
    return MessageModel(
      id: json['id'] as String,
      messId: json['mess_id'] as String,
      userId: json['user_id'] as String,
      senderName: json['sender_name'] as String? ?? 'Unknown',
      message: json['message'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'mess_id': messId,
      'user_id': userId,
      'sender_name': senderName,
      'message': message,
      // 'id' and 'created_at' are typically auto-generated by Supabase
    };
  }
}
