import 'package:cloud_firestore/cloud_firestore.dart';

class RequestModel {
  final String id;
  final String messId;
  final String userId;
  final String type; // 'meal' or 'leave'
  final String status; // 'pending', 'approved', 'rejected'
  final String? details;
  final DateTime createdAt;
  
  // Joined fields from profiles
  final String? userName;

  RequestModel({
    required this.id,
    required this.messId,
    required this.userId,
    required this.type,
    required this.status,
    this.details,
    required this.createdAt,
    this.userName,
  });

  factory RequestModel.fromJson(Map<String, dynamic> json) {
    return RequestModel(
      id: json['id'] as String,
      messId: json['mess_id'] as String,
      userId: json['user_id'] as String,
      type: json['type'] as String,
      status: json['status'] as String,
      details: json['details'] as String?,
      createdAt: json['created_at'] is Timestamp ? (json['created_at'] as Timestamp).toDate() : DateTime.parse(json['created_at'] as String),
      userName: json['profiles']?['full_name'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'mess_id': messId,
      'user_id': userId,
      'type': type,
      'status': status,
      'details': details,
      // id and created_at are generated by DB typically on insert
    };
  }
}
